# Generated by Django 3.2.18 on 2023-03-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_channelfilter_filtering_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='is_restricted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='alertgroupcounter',
            name='current_month',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='alertgroupcounter',
            name='value_this_month',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
