# Generated by Django 3.2.18 on 2023-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_organization_cluster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gcom_org_contract_type',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gcom_org_has_irm_sku',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
